plugins {
    id "com.android.application"
}

android {
    namespace "com.rickrjqin.deepseekbalance"
        compileSdk 36

    defaultConfig {
        applicationId "com.rickrjqin.deepseekbalance"
        minSdk 26
        targetSdk 36
        versionCode 6
        versionName "1.2.1"
    }

    signingConfigs {
        release {
            storeFile file("release.keystore")
            storePassword "deepseek-balance"
            keyAlias "deepseek"
            keyPassword "deepseek-balance"
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.release
        }
    }
}
